export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const TODO_REDUCERS = new Set(
	[ADD_TODO, DELETE_TODO, EDIT_TODO,
		COMPLETE_TODO, COMPLETE_ALL, CLEAR_COMPLETED,
	]);